baseURL = "https://williamteo.github.io/"
languageCode = "en-us"
title = "From William's Desk"
theme = "beautifulhugo"
disqusShortname = "williamteo"
googleAnalytics = "G-KDQT4L3GWH"
metaDataFormat = "yaml"
enableGitInfo = true

[params]
  # subtitle = ""
  mainSections = ["post","posts"]
  # logo = "img/avatar-icon.png"
  # favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  # commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  showRelatedPosts = true
  commit = "https://github.com/williamteo/williamteo.github.io/tree/"
  #  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[permalinks]
  post = "/:year/:month/:title/"

[author]
  name = "William Teo"
  website = "https://www.william-teo.com"
  linkedin = "willteo"

[[menu.main]]
  name = "Blog"
  url = "post"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3


